### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by JeffreyWay** [laracasts/blog#2]
https://github.com/laracasts/blog/blob/c2d079a8981f7ea801ea59c0a91d2dde694335fa/build-a-simple-online-store-using-laravel-folio-livewire-v3-and-volt.md?plain=1#L77

What home page? We didn't register anything at this point. You'd get a 404 if you view the site in the browser.

https://github.com/laracasts/blog/blob/c2d079a8981f7ea801ea59c0a91d2dde694335fa/build-a-simple-online-store-using-laravel-folio-livewire-v3-and-volt.md?plain=1#L113

I think that'll instead create 'resources/views/livewire/cart.blade.php', right? 

https://github.com/laracasts/blog/blob/c2d079a8981f7ea801ea59c0a91d2dde694335fa/build-a-simple-online-store-using-laravel-folio-livewire-v3-and-volt.md?plain=1#L173

Are you sure that Folio automatically creates a route? I'm not well-versed in Volt, make:volt just creates the component, yeah? There's no registered route at this point.

**Comment by JeffreyWay** [comment]
I'll append to this as I work through your article.

**Comment by benjamincrozat** [comment]
@JeffreyWay Fixed all the steps, it all makes sense now. I suggest you try to reproduce the project locally. 🙂 The goal here is to leverage Folio to avoid creating any route. As you know, the pages folder is where it starts. And Volt can look up for components inside as well.
